server:
  port: 8081
spring:
  application:
    name: users-service
  datasource:
    url: jdbc:mysql://localhost:3306/users_db
    username: root
    password: password
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/