server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/users/**
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/api/accounts/**
        - id: transactions-service
          uri: lb://transactions-service
          predicates:
            - Path=/api/transactions/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/