server:
  port: 8083
spring:
  application:
    name: transactions-service
  datasource:
    url: jdbc:mysql://localhost:3306/transactions_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/