server:
  port: 8084
spring:
  application:
    name: notifications-service
  rabbitmq:
    host: localhost
    port: 5672
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/