server:
  port: 8082
spring:
  application:
    name: accounts-service
  datasource:
    url: jdbc:mysql://localhost:3306/accounts_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/